
services:
  pqc-server:
    build: ./client
    container_name: client
    hostname: client
    networks:
      pqc-net:
        ipv4_address: 192.168.1.102
    volumes:
      - ./pi-talking:/app

  pqc-client:
    build: ./server
    container_name: server
    hostname: server
    depends_on:
      - pqc-client
    networks:
      pqc-net:
        ipv4_address: 192.168.1.101
    volumes:
      - ./pi-talking:/app

networks:
  pqc-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
